/**
 * GENERATED by scripts/build-ncr-pincodes.mjs — do not edit by hand.
 * Source: India Post pincode directory (api.postalpincode.in), fetched 2026-09-16.
 * See the script header for the inclusion rule.
 */

export type PincodeEntry = {
  pincode: string;
  /** Post office names at this pincode, lightly tidied for display. */
  localities: string[];
  /** India Post district. Delhi only, where one city spans eleven districts. */
  district?: string;
};

export type CityPincodes = {
  pincodes: PincodeEntry[];
  /** Well-known localities, each verified as a post office at its pincode. */
  featured: { name: string; pincode: string }[];
};

export const NCR_PINCODES_FETCHED_ON = "2026-09-16";

export const NCR_PINCODES = {
  "delhi": {
    "pincodes": [
      {
        "pincode": "110001",
        "localities": [
          "Baroda House",
          "Bengali Market",
          "Bhagat Singh Market",
          "Connaught Place",
          "Constitution House",
          "Election Commission",
          "Janpath",
          "Krishi Bhawan",
          "Lady Harding Medical College",
          "New",
          "North Avenue",
          "Parliament House",
          "Patiala House",
          "Pragati Maidan",
          "Pragati Maidan Camp",
          "Rail Bhawan",
          "Sansad Marg",
          "Sansadiya Soudh",
          "Secretariat North",
          "Shastri Bhawan",
          "Supreme Court"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110002",
        "localities": [
          "A.G.C.R.",
          "Ajmeri Gate Extn.",
          "Darya Ganj",
          "Gandhi Smarak Nidhi",
          "I.P.Estate",
          "Indraprastha",
          "Minto Road"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110003",
        "localities": [
          "Aliganj",
          "C G O Complex",
          "Delhi High Court",
          "Delhi High Court Extension Counter",
          "Golf Links",
          "Kasturba Nagar",
          "Lodi Road",
          "Pandara Road",
          "Pragati Vihar",
          "Safdarjung Air Port"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110004",
        "localities": [
          "Rashtrapati Bhawan"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110005",
        "localities": [
          "Anand Parbat",
          "Anand Parbat Indl. Area",
          "Bank Street",
          "Desh Bandhu Gupta Road",
          "Guru Gobind Singh Marg",
          "Karol Bagh",
          "Master Prithvi Nath Marg",
          "Sat Nagar"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110006",
        "localities": [
          "Baratooti",
          "Chandni Chowk",
          "Chawri Bazar",
          "Dareeba",
          "Delhi Sadar Bazar",
          "Hauz Qazi",
          "Jama Masjid",
          "S.T. Road"
        ],
        "district": "North Delhi"
      },
      {
        "pincode": "110007",
        "localities": [
          "C.C.I.",
          "Delhi University",
          "Gulabi Bagh",
          "Jawahar Nagar",
          "Kamla Nagar",
          "Malka Ganj",
          "Padam Nagar",
          "R.C.A.O.",
          "Rana Pratap Bagh",
          "Roop Nagar",
          "Roshan Ara Road",
          "Shakti Nagar"
        ],
        "district": "North Delhi"
      },
      {
        "pincode": "110008",
        "localities": [
          "Dada Ghosh Bhawan",
          "Patel Nagar",
          "Patel Nagar East",
          "Patel Nagar South",
          "Patel Nagar West"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110009",
        "localities": [
          "Dr.Mukerjee Nagar",
          "G.T.B.Nagar",
          "Gujranwala Colony",
          "H.S.Sangh",
          "Model Town II",
          "Model Town III",
          "Nirankari Colony"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110010",
        "localities": [
          "505 A B Workshop",
          "A F Palam",
          "Aps Colony",
          "Bazar Road",
          "C.V.D.",
          "COD",
          "Delhi Cantt",
          "Dhaula Kuan",
          "Kirby Place",
          "Pinto Park",
          "R R Hospital",
          "Signal Enclave",
          "Station Road",
          "Subroto Park"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110011",
        "localities": [
          "Nirman Bhawan",
          "South Avenue",
          "Udyog Bhawan"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110012",
        "localities": [
          "I.A.R.I.",
          "Inderpuri",
          "National Physical Laboratory"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110013",
        "localities": [
          "Dargah Sharif",
          "Hazrat Nizamuddin"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110014",
        "localities": [
          "Hari Nagar Ashram",
          "Jeevan Nagar",
          "Jungpura",
          "Pratap Market"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110015",
        "localities": [
          "Delhi Industrial Area",
          "ESI",
          "Karam Pura",
          "L. M. Nagar Indl. Area",
          "Mansarover Garden",
          "N.I.Area",
          "Ramesh Nagar",
          "Zakhira"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110016",
        "localities": [
          "Green Park Market",
          "Hauz Khas",
          "Hauz Khas Market",
          "IT Hauz Khas",
          "NIE Campus",
          "Technology Bhawan"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110017",
        "localities": [
          "Distt. Court Complex, Saket",
          "Malviya Nagar",
          "MMTC/STC Colony",
          "Panchsheel Enclave",
          "Pushp Vihar",
          "Saket",
          "Sarvodya Enclave",
          "South Malviya Nagar"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110018",
        "localities": [
          "Ashok Nagar",
          "Chand Nagar",
          "Chaukhandi",
          "Fateh Nagar",
          "Khyala Phase - I",
          "Khyala Phase - II",
          "M.B.S. Nagar",
          "Mahabir Nagar",
          "Tilak Nagar",
          "Tilak Nagar East",
          "Vikas Puri",
          "Vishnu Garden"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110019",
        "localities": [
          "Alaknanda",
          "Chittranjan Park",
          "Kalkaji",
          "Nehru Place"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110020",
        "localities": [
          "C R R I",
          "F F C Okhla",
          "Okhla Industrial Area Phase-i",
          "Okhla Industrial Estate",
          "Tehkhand"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110021",
        "localities": [
          "Anand Niketan",
          "Chanakya Puri",
          "Malcha Marg",
          "Moti Bagh",
          "Nanak Pura",
          "South Delhi Campus"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110022",
        "localities": [
          "R K Puram Sect-1",
          "R K Puram Sect-12",
          "R K Puram Sect-3",
          "R K Puram Sect-4",
          "R K Puram Sect-5",
          "R K Puram Sect-8",
          "R K Puram Sect7",
          "R K Puram Sector - 6 Postal SB"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110023",
        "localities": [
          "Kidwai Nagar East",
          "Kidwai Nagar West",
          "Laxmi Bai Nagar",
          "Netaji Nagar",
          "Sarojini Nagar"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110024",
        "localities": [
          "Amar Colony",
          "Defence Colony",
          "Krishna Market",
          "Lajpat Nagar"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110025",
        "localities": [
          "Abul Fazal Enclave-I",
          "Jamia Nagar",
          "New Friends Colony",
          "Sukhdev Vihar",
          "Zakir Nagar"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110026",
        "localities": [
          "Ashoka Park Extn.",
          "Punjabi Bagh",
          "Punjabi Bagh Sec - III",
          "Shivaji Park"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110027",
        "localities": [
          "Janta Market",
          "Rajouri Garden J-6",
          "Rajouri Market",
          "Subhash Nagar",
          "Subhash Nagar West",
          "Tagore Garden"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110028",
        "localities": [
          "Kair",
          "Khaira",
          "Naraina Industrial Estate",
          "Naraina Village"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110029",
        "localities": [
          "Ansari Nagar",
          "Nauroji Nagar",
          "Safdarjung Enclave"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110030",
        "localities": [
          "Gadaipur",
          "Ghitorni",
          "Lado Sarai",
          "Mehrauli",
          "Paryavaran Complex",
          "Sultanpur",
          "T B Hospital"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110031",
        "localities": [
          "Gandhi Nagar",
          "Gandhi Nagar Bazar",
          "Geeta Colony",
          "Kailash Nagar",
          "Raghubar Pura",
          "Rajgarh Colony",
          "Shastri Nagar"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110032",
        "localities": [
          "Babarpur",
          "Balbir Nagar",
          "Bhola Nath Nagar",
          "Distt. Court",
          "Goverdhan Bihari Colony",
          "Loni Road",
          "Man Sarovar Park",
          "Rohtash Nagar",
          "Shahdara",
          "Shahdara Mandi",
          "Shivaji Park",
          "Telewara",
          "Vishwas Nagar"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110033",
        "localities": [
          "Adrash Nagar",
          "Bhalaswa",
          "Jahangir Puri A Block",
          "Jahangir Puri D Block",
          "Jahangir Puri H Block",
          "N.S.Mandi"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110034",
        "localities": [
          "Anandvas Shakurpur",
          "Maurya Enclave",
          "Rani Bagh",
          "Saraswati Vihar",
          "Shakur Pur I Block",
          "Shakurbasti Rs",
          "Sri Nagar Colony"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110035",
        "localities": [
          "Ganeshpura",
          "Keshav Puram",
          "Onkar Nagar",
          "Power House",
          "Rampura",
          "Sarai Rohilla"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110036",
        "localities": [
          "Alipur",
          "Bakhtawar Pur",
          "Bakoli",
          "Hiranki",
          "Kadipur",
          "Khampur",
          "Mukhmelpur",
          "Nangal Poona",
          "Palla",
          "Tajpur Kalan"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110037",
        "localities": [
          "Gurgaon Road",
          "IGI Airport",
          "Mahipalpur",
          "Nangal Dewat",
          "Palam Airport"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110038",
        "localities": [
          "A F Rajokari",
          "Rajokari"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110039",
        "localities": [
          "Auchandi",
          "Barwala",
          "Bawana",
          "Daryapur Kalan",
          "Ghoga",
          "Hareveli",
          "Jat Khore",
          "Katewara",
          "Mungeshpur",
          "Nangal Thakran",
          "Pooth Khurd",
          "Qutabagarh"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110040",
        "localities": [
          "Bankner",
          "Bhorgarh",
          "Kanya Gurukul",
          "Lampur",
          "Narela",
          "Sanoth",
          "Singhu",
          "Tikri Khurd"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110041",
        "localities": [
          "Bakkarwala",
          "Hirankudna",
          "Mundka",
          "Nangloi",
          "Nangloi - II",
          "Nangloi - III",
          "Nilothi",
          "Ranhola",
          "Tikri Kalan"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110042",
        "localities": [
          "Badli",
          "Delhi Engg. College",
          "Pehlad Pur",
          "Samai Pur",
          "Shahbad Daulatpur",
          "Siraspur"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110043",
        "localities": [
          "Baprola",
          "Daulatpur",
          "Dichaun Kalan",
          "Dindarpur",
          "Jhatikara",
          "Mitraon",
          "Najafgarh",
          "Pandwala Kalan",
          "Papravat",
          "Rewla Khanpur",
          "Surehra",
          "Tilangpur Kotla"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110044",
        "localities": [
          "Badarpur",
          "BTPS",
          "Jaitpur",
          "Lal Kuan",
          "Molarband",
          "Pul Pahladpur",
          "Tugalkabad",
          "Tugalkabad Railway Colony"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110045",
        "localities": [
          "Dabri",
          "Indira Park",
          "Nasirpur",
          "Palam Village"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110046",
        "localities": [
          "Nangal Raya",
          "Sagarpur"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110047",
        "localities": [
          "Arjungarh",
          "Aya Nagar",
          "Jaunapur",
          "Mandi"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110048",
        "localities": [
          "Greater Kailash",
          "Kailash Colony",
          "Masjid Moth"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110049",
        "localities": [
          "Andrewsganj",
          "Gautam Nagar",
          "Gulmohar Park",
          "New Delhi South Ext-II",
          "Sadiq Nagar",
          "Sahpurjat"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110051",
        "localities": [
          "Azad Nagar",
          "Govind Pura",
          "Krishna Nagar",
          "Ram Nagar"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110052",
        "localities": [
          "Ashok Vihar",
          "Nimri",
          "Satyawati Nagar",
          "Shastri Nagar",
          "Wazir Pur III"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110053",
        "localities": [
          "Bhajan Pura",
          "Brahampuri",
          "Garhi Mandu",
          "Ghonda",
          "Jafrabad",
          "Jagjit Nagar",
          "Maujpur",
          "New Usmanpur",
          "Seelampur",
          "Yamuna Vihar"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110054",
        "localities": [
          "Aruna Nagar",
          "Civil Lines",
          "District Courts",
          "Majnu ka Tila",
          "Patrachar Vidyalay",
          "Timarpur"
        ],
        "district": "North Delhi"
      },
      {
        "pincode": "110055",
        "localities": [
          "A.K.Market",
          "Multani Dhanda",
          "Pahar Ganj",
          "Swami Ram Tirth Nagar"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110056",
        "localities": [
          "New Multan Nagar",
          "Shakur Basti Depot"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110057",
        "localities": [
          "Vasant Vihar-1",
          "Vasant Vihar-2"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110058",
        "localities": [
          "D.E.S.U. Colony",
          "Jail Road",
          "Janakpuri A-3",
          "Janakpuri B-1",
          "Janakpuri C-4"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110059",
        "localities": [
          "D. K. Mohan Garden",
          "Hastal Village",
          "Jeevan Park",
          "Matiala",
          "Uttam Nagar"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110060",
        "localities": [
          "Rajender Nagar"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110061",
        "localities": [
          "Bijwasan",
          "Shahbad Mohammadpur"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110062",
        "localities": [
          "Air Force Station Tugalkabad",
          "BSF Camp Tigri",
          "Dakshinpuri Phase-I",
          "Dakshinpuri Phase-II",
          "Dakshinpuri Phase-III",
          "Deoli",
          "Dr. Ambedkar Nagar",
          "Hamdard Nagar",
          "Khanpur",
          "Pushpa Bhawan",
          "Talimabad"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110063",
        "localities": [
          "Jawala Heri",
          "Madipur Slum Quarter",
          "Madipur Village",
          "Paschim Vihar",
          "Paschim Vihar B Block",
          "Peeragarhi"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110064",
        "localities": [
          "Hari Nagar",
          "Hari Nagar BE Block",
          "Hari Nagar Dadb Block",
          "Maya Puri",
          "Mayapuri Shopping Centre"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110065",
        "localities": [
          "East Of Kailash",
          "East Of Kailash Phase-I",
          "Nehru Nagar",
          "Sant Nagar",
          "Sriniwaspuri"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110066",
        "localities": [
          "R K Puram",
          "R K Puram West"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110067",
        "localities": [
          "J.N.U.",
          "JNU New Campus",
          "Munirka"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110068",
        "localities": [
          "Ignou",
          "Maidan Garhi"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110069",
        "localities": [
          "Union Public Service Commission"
        ],
        "district": "Central Delhi"
      },
      {
        "pincode": "110070",
        "localities": [
          "Masood Pur",
          "Vasant Kunj",
          "Vasant Kunj Pkt-A"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110071",
        "localities": [
          "Badusarai",
          "Chhawla",
          "DC Goyla",
          "Kangan Heri"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110072",
        "localities": [
          "CRPF Jharoda Kalan",
          "Jharoda Kalan"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110073",
        "localities": [
          "Dhansa",
          "Galib Pur",
          "Ghuman Hera",
          "Issapur",
          "Jafarpur",
          "Khera Dabur",
          "Malik Pur",
          "Mundela Kalan",
          "Quazipur",
          "Raota",
          "Ujwa"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110074",
        "localities": [
          "C.S.K.M. School",
          "Chandanhoola",
          "Chattarpur",
          "Dera",
          "Fatehpur Beri",
          "Sanjay Colony Bhati Mines",
          "Satbari",
          "Sawan Public School"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110075",
        "localities": [
          "Amberhai",
          "District Court Complex Dwarka",
          "Dwarka Sec-6"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110076",
        "localities": [
          "Ali",
          "Madanpur Khadar",
          "Sarita Vihar"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110077",
        "localities": [
          "Bagdola",
          "Barthal",
          "Dhulsiras",
          "Palam Extn",
          "Raj Nagar - II"
        ],
        "district": "South West Delhi"
      },
      {
        "pincode": "110078",
        "localities": [
          "Distt. Court Complex, Dwarka",
          "GGSIP University",
          "Kakrola",
          "N.S.I.T. Dwarka"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110080",
        "localities": [
          "Sangam Vihar"
        ],
        "district": "South Delhi"
      },
      {
        "pincode": "110081",
        "localities": [
          "Chand Pur",
          "Gheora",
          "Jaunti",
          "Kanjhawla",
          "Karala",
          "Lad Pur",
          "Majra Dabas",
          "Mubarak Pur Dabas",
          "Nizampur",
          "Punjab Khor",
          "Rani Khera"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110082",
        "localities": [
          "Holambi Kalan",
          "Khera Kalan",
          "Khera Khurd",
          "Naya Bans"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110083",
        "localities": [
          "Mangolpuri A Block",
          "Mangolpuri I Block",
          "Mangolpuri N Block",
          "Mangolpuri S Block"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110084",
        "localities": [
          "Burari",
          "Jagatpur",
          "Jharoda Majraa",
          "Wazirabad Village"
        ],
        "district": "North Delhi"
      },
      {
        "pincode": "110085",
        "localities": [
          "Avantika",
          "Naharpur",
          "Prashant Vihar",
          "Rithala",
          "Rohini Courts",
          "Rohini sec-11",
          "Rohini Sector 5",
          "Rohini Sector-7"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110086",
        "localities": [
          "Begumpur",
          "Budh Vihar",
          "Pooth Kalan",
          "Pooth Kalan Resettlement",
          "Prem Nagar",
          "Sultanpuri B Block",
          "Sultanpuri C Block",
          "Sultanpuri F Block"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110087",
        "localities": [
          "Jwala Puri",
          "Sunder Vihar"
        ],
        "district": "West Delhi"
      },
      {
        "pincode": "110088",
        "localities": [
          "Haiderpur",
          "Shalamar",
          "Shalimar Bagh"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110089",
        "localities": [
          "Rohini Sector 15"
        ],
        "district": "North West Delhi"
      },
      {
        "pincode": "110090",
        "localities": [
          "Badarpur Khadar",
          "Karawal Nagar",
          "Shaheed Bhagat Singh Colony",
          "Shriram Colony Rajeev Nagar",
          "Sonia Vihar"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110091",
        "localities": [
          "Chilla",
          "Himmatpuri",
          "Kalyanpuri",
          "Kalyanvas",
          "Mayur Vihar Ph-I",
          "Patparganj",
          "Trilok Puri"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110092",
        "localities": [
          "Anand Vihar",
          "IP Extension",
          "Laxmi Nagar",
          "Mandawali Fazalpur",
          "Nirman Vihar",
          "Shakarpur",
          "Surajmal Vihar",
          "Yozna Vihar"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110093",
        "localities": [
          "Harsh Vihar",
          "Loni Road Housing Complex",
          "Mandoli Saboli",
          "Nand Nagri \"A\"",
          "Nand Nagri \"C\"",
          "Sunder Nagari"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110094",
        "localities": [
          "Dayalpur",
          "Gokal Puri",
          "Johripur",
          "Khazuri Khas",
          "Sabhapur"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110095",
        "localities": [
          "Dilshad Garden",
          "G.T.B. Hospital",
          "Jhilmil",
          "Jhilmil Tahirpur",
          "New Seemapuri",
          "Old Seemapuri",
          "V.K. Nagar",
          "Vivek Vihar"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110096",
        "localities": [
          "Ghazipur",
          "Mayur Vihar Ph-III",
          "Vasundhra Enclave"
        ],
        "district": "East Delhi"
      },
      {
        "pincode": "110097",
        "localities": [
          "Kapashera."
        ],
        "district": "South West Delhi"
      }
    ],
    "featured": [
      {
        "name": "Saket",
        "pincode": "110017"
      },
      {
        "name": "Lajpat Nagar",
        "pincode": "110024"
      },
      {
        "name": "Janakpuri",
        "pincode": "110058"
      },
      {
        "name": "Dwarka",
        "pincode": "110075"
      },
      {
        "name": "Rohini",
        "pincode": "110085"
      }
    ]
  },
  "noida": {
    "pincodes": [
      {
        "pincode": "201301",
        "localities": [
          "Sector 12",
          "Sector 16"
        ]
      },
      {
        "pincode": "201303",
        "localities": [
          "Sector 30",
          "Sector 37",
          "Sector 45"
        ]
      },
      {
        "pincode": "201304",
        "localities": [
          "Baraula",
          "Chhaprauli Bengar",
          "Gejha",
          "Maharishi Nagar"
        ]
      },
      {
        "pincode": "201305",
        "localities": [
          "Nagla Charandas",
          "Nepz Post Office"
        ]
      },
      {
        "pincode": "201307",
        "localities": [
          "Chhajarsi",
          "Sector 34",
          "Sector 55",
          "Parthala Khanjarpur",
          "Sarfabad"
        ]
      },
      {
        "pincode": "201309",
        "localities": [
          "Khora Gaon",
          "Sector 62"
        ]
      },
      {
        "pincode": "201313",
        "localities": [
          "Amity University"
        ]
      }
    ],
    "featured": [
      {
        "name": "Sector 16",
        "pincode": "201301"
      },
      {
        "name": "Sector 37",
        "pincode": "201303"
      },
      {
        "name": "Sector 55",
        "pincode": "201307"
      },
      {
        "name": "Sector 62",
        "pincode": "201309"
      }
    ]
  },
  "greater-noida": {
    "pincodes": [
      {
        "pincode": "201306",
        "localities": [
          "Bisrakh",
          "I.A. Surajpur",
          "Kulesra",
          "Sakipur",
          "Tilapta Karanwas"
        ]
      },
      {
        "pincode": "201310",
        "localities": [
          "Alpha",
          "Ghori",
          "Kasna",
          "Knowledge Park-I",
          "Maicha",
          "Tugalpur"
        ]
      },
      {
        "pincode": "201312",
        "localities": [
          "Gautam Budh University"
        ]
      }
    ],
    "featured": [
      {
        "name": "Alpha",
        "pincode": "201310"
      },
      {
        "name": "Knowledge Park",
        "pincode": "201310"
      },
      {
        "name": "Bisrakh",
        "pincode": "201306"
      },
      {
        "name": "Surajpur",
        "pincode": "201306"
      }
    ]
  },
  "gurgaon": {
    "pincodes": [
      {
        "pincode": "122001",
        "localities": [
          "Arjun Nagar",
          "Basai Road",
          "Gurgaon Kty.",
          "Sector 17",
          "Gurgaon South City I",
          "Khandsa Road",
          "Mini Sectt.",
          "New Colony",
          "Shivaji Nagar",
          "Sohna Adda",
          "Urban Estate"
        ]
      },
      {
        "pincode": "122002",
        "localities": [
          "Chakkarpur",
          "DLF QE",
          "Nathupur"
        ]
      },
      {
        "pincode": "122003",
        "localities": [
          "Sector 45",
          "Gwal Pahari",
          "Jharsa",
          "Smaspur",
          "Wazirabad"
        ]
      },
      {
        "pincode": "122004",
        "localities": [
          "Khandsa",
          "Kherki Daula",
          "Lakhnaula",
          "Narsinghpur",
          "Sikanderpur",
          "Sikohpur"
        ]
      },
      {
        "pincode": "122005",
        "localities": [
          "Air Force"
        ]
      },
      {
        "pincode": "122006",
        "localities": [
          "Basai",
          "Daultabad",
          "Gurgaon Village",
          "Railwary Road"
        ]
      },
      {
        "pincode": "122007",
        "localities": [
          "Industrial Estate"
        ]
      },
      {
        "pincode": "122008",
        "localities": [
          "DLF Ph-II"
        ]
      },
      {
        "pincode": "122009",
        "localities": [
          "Galleria DLF-IV"
        ]
      },
      {
        "pincode": "122010",
        "localities": [
          "DLF Ph-III"
        ]
      },
      {
        "pincode": "122011",
        "localities": [
          "Sector 56"
        ]
      },
      {
        "pincode": "122015",
        "localities": [
          "Palam Road",
          "Sarhaul"
        ]
      },
      {
        "pincode": "122016",
        "localities": [
          "Dundahera",
          "Industrial Complex Dundahera"
        ]
      },
      {
        "pincode": "122017",
        "localities": [
          "Carterpuri",
          "Palam Vihar"
        ]
      },
      {
        "pincode": "122018",
        "localities": [
          "Gurgaon South City II"
        ]
      },
      {
        "pincode": "122051",
        "localities": [
          "Kasan",
          "Manesar",
          "Nsg Camp Manesar"
        ]
      },
      {
        "pincode": "122052",
        "localities": [
          "IMT Manesar"
        ]
      },
      {
        "pincode": "122101",
        "localities": [
          "Badshahpur",
          "Fazilpur",
          "Kadipur",
          "Paltra",
          "Teekli"
        ]
      }
    ],
    "featured": [
      {
        "name": "DLF Ph-II",
        "pincode": "122008"
      },
      {
        "name": "DLF Ph-III",
        "pincode": "122010"
      },
      {
        "name": "Sector 56",
        "pincode": "122011"
      },
      {
        "name": "South City II",
        "pincode": "122018"
      },
      {
        "name": "Palam Vihar",
        "pincode": "122017"
      }
    ]
  },
  "ghaziabad": {
    "pincodes": [
      {
        "pincode": "201001",
        "localities": [
          "Ashok Nagar",
          "Nehru Nagar",
          "Ramte Ram Road"
        ]
      },
      {
        "pincode": "201002",
        "localities": [
          "Ingram Institute",
          "Kamla Nehru Nagar",
          "Kavi Nagar",
          "New Raj Nagar",
          "Old Raj Nagar",
          "Police Line Harsaon",
          "Raispur",
          "Rajapur",
          "RAKNPA",
          "Sadarpur",
          "Shahpur Bamheta",
          "Shastri Nagar",
          "Vivekanand Nagar"
        ]
      },
      {
        "pincode": "201003",
        "localities": [
          "Ator Nagla",
          "Aurangabad Ristal",
          "Bhup Kheri",
          "Farrukh Nagar",
          "Meerut Road",
          "Morta",
          "Nistoli"
        ]
      },
      {
        "pincode": "201004",
        "localities": [
          "Hindon Air Field"
        ]
      },
      {
        "pincode": "201005",
        "localities": [
          "Bhopura",
          "Pasonda",
          "Sahibabad"
        ]
      },
      {
        "pincode": "201006",
        "localities": [
          "Chikamberpur"
        ]
      },
      {
        "pincode": "201007",
        "localities": [
          "Mohan Nagar"
        ]
      },
      {
        "pincode": "201009",
        "localities": [
          "Arya Nagar",
          "B.B.Nagar",
          "Chhaprola",
          "Chhipyana",
          "Dasna Gate Ed",
          "Dundahera",
          "Ghaziabad City",
          "Kaila",
          "Model Town",
          "Nasratpura ED",
          "Roza Yakubpur",
          "Vijai Nagar"
        ]
      },
      {
        "pincode": "201010",
        "localities": [
          "Bharat Nagar",
          "Hasanpur Bhowapur",
          "I.E.Sahibabad"
        ]
      },
      {
        "pincode": "201011",
        "localities": [
          "Chander Nagar"
        ]
      },
      {
        "pincode": "201012",
        "localities": [
          "Kaushambi",
          "Vasundhra"
        ]
      },
      {
        "pincode": "201013",
        "localities": [
          "Govindpuram"
        ]
      },
      {
        "pincode": "201014",
        "localities": [
          "Makanpur",
          "Shipra Sun City"
        ]
      },
      {
        "pincode": "201015",
        "localities": [
          "Adhyatmic Nagar",
          "Dasna",
          "Dasna R.S.",
          "Galand",
          "Hassanpur",
          "Hindan Nagar",
          "Jindal Nagar",
          "Kushlia",
          "Nahal",
          "Udai Rampur Nagla"
        ]
      },
      {
        "pincode": "201016",
        "localities": [
          "Crossing Republik"
        ]
      },
      {
        "pincode": "201017",
        "localities": [
          "Raj Nagar Extension"
        ]
      },
      {
        "pincode": "201019",
        "localities": [
          "Vaishali"
        ]
      },
      {
        "pincode": "201102",
        "localities": [
          "Badshahnpur Siroli",
          "Behta Hazipur",
          "Chirori",
          "Jaoli",
          "Loni",
          "Mandola",
          "Teela Sahbazpur"
        ]
      },
      {
        "pincode": "201103",
        "localities": [
          "Tronica City"
        ]
      }
    ],
    "featured": [
      {
        "name": "Vaishali",
        "pincode": "201019"
      },
      {
        "name": "Kaushambi",
        "pincode": "201012"
      },
      {
        "name": "Crossing Republik",
        "pincode": "201016"
      },
      {
        "name": "Raj Nagar Extension",
        "pincode": "201017"
      }
    ]
  },
  "faridabad": {
    "pincodes": [
      {
        "pincode": "121001",
        "localities": [
          "Factory Area",
          "Faridabad NIT",
          "Feroz Gandhi Nagar",
          "Industrial Area",
          "N.I.F.M.",
          "Nh-2",
          "Nh-3",
          "Nh-4"
        ]
      },
      {
        "pincode": "121002",
        "localities": [
          "Bhaskola",
          "Faridabad City",
          "Sector 16",
          "Sector 16a",
          "Sector 18",
          "Kheri Kalan"
        ]
      },
      {
        "pincode": "121003",
        "localities": [
          "Amarnagar",
          "Anangpur",
          "Gurukul Indraprashtha",
          "Mathura Road",
          "Tilpat"
        ]
      },
      {
        "pincode": "121004",
        "localities": [
          "Amarpur",
          "Atali",
          "Ballabgarh",
          "Baroli",
          "Chawla Colony Ballabgarh",
          "Chhainsa",
          "Dayalpur",
          "Deeg",
          "Dhauj",
          "E C Dhauj",
          "Sector 3",
          "Fatehpur Billoch",
          "Fatehpur Tagga",
          "Gadpuri",
          "Gonchhi",
          "Jawan",
          "Machhgar",
          "Mohna",
          "N.T.P.C./sector-10",
          "Neemka",
          "Pali",
          "Panhera Khurd",
          "Sagarpur",
          "Seekri"
        ]
      },
      {
        "pincode": "121005",
        "localities": [
          "Sector 22",
          "Jawahar Colony"
        ]
      },
      {
        "pincode": "121006",
        "localities": [
          "Sector 7",
          "Sector 8",
          "Sector 9",
          "G.T. Road"
        ]
      },
      {
        "pincode": "121007",
        "localities": [
          "Escortsnagar",
          "Sector 12",
          "Sector 15"
        ]
      },
      {
        "pincode": "121008",
        "localities": [
          "Sector 29"
        ]
      },
      {
        "pincode": "121009",
        "localities": [
          "Surajkund"
        ]
      },
      {
        "pincode": "121010",
        "localities": [
          "Nhpc Colony"
        ]
      },
      {
        "pincode": "121012",
        "localities": [
          "Sector 21D"
        ]
      },
      {
        "pincode": "121013",
        "localities": [
          "Sector 91"
        ]
      }
    ],
    "featured": [
      {
        "name": "NIT",
        "pincode": "121001"
      },
      {
        "name": "Sector 16",
        "pincode": "121002"
      },
      {
        "name": "Ballabgarh",
        "pincode": "121004"
      },
      {
        "name": "Surajkund",
        "pincode": "121009"
      }
    ]
  }
} as const satisfies Record<string, CityPincodes>;
